services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data

  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "python",
        "/code/manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.production
    depends_on:
      - db
      - cache
